# General Settings
# docs: https://github.com/tak-bro/aicommit2
# defaults: https://github.com/tak-bro/aicommit2/blob/main/src/utils/config.ts
logging = true
temperature = 0.8
locale = "zh-CN"
generate = 3

[DEEPSEEK]
key = ""

# aliyun openai compatible-mode
# https://help.aliyun.com/zh/model-studio/getting-started/models#0d841ef5caz0x
[OPENAI]
key = ""
url = "https://dashscope.aliyuncs.com"
path = "/compatible-mode/v1"
model = "llama3-8b-instruct"
