# General Settings
# docs: https://github.com/tak-bro/aicommit2
# defaults: https://github.com/tak-bro/aicommit2/blob/main/src/utils/config.ts
logging = false
temperature = 0.8
locale = "zh"
generate = 3

[DEEPSEEK]
key = ""

# openai sdk compatibility mode using aliyun service
# https://help.aliyun.com/zh/model-studio/getting-started/models
[OPENAI]
key = ""
url = "https://dashscope.aliyuncs.com/"
path = "/compatible-mode/v1/chat/completions"
model = "qwen2.5-3b-instruct"

#####################################################################
# openai sdk compatibility mode using bytedance service
# https://console.volcengine.com/ark/region:ark+cn-beijing/endpoint
#####################################################################
# [OPENAI]
# key = ""
# url = "https://ark.cn-beijing.volces.com"
# path = "/api/v3/chat/completions"
# model = "ep-20241218041000-98pm7"

#####################################################################
# openai sdk compatibility mode using tencent service
# https://cloud.tencent.com/document/product/1729/111007
#####################################################################
# [OPENAI]
# key = ""
# url = "https://api.hunyuan.cloud.tencent.com"
# path = "/v1/chat/completions"
# model = "hunyuan-pro"

#####################################################################
# openai sdk compatibility mode using bigmodel service
# https://open.bigmodel.cn/dev/api/thirdparty-frame/openai-sdk
#####################################################################
# [OPENAI]
# key = ""
# url = "https://open.bigmodel.cn"
# path = "/api/paas/v4/chat/completions"
# model = "glm-4"

#####################################################################
# openai sdk compatibility mode using siliconflow service
# https://docs.siliconflow.cn/quickstart
#####################################################################
# [OPENAI]
# key = ""
# url = "https://api.siliconflow.cn"
# path = "/v1/chat/completions"
# model = "Qwen/Qwen2.5-7B-Instruct"
