# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# defaults keymaps: https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml
# docs: https://yazi-rs.github.io/docs/configuration/keymap
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on = "d"
run = "yank --cut"
desc = "Yank selected files (cut)"

[[manager.prepend_keymap]]
on = "D"
run = "unyank"
desc = "Cancel the yank status"

[[manager.prepend_keymap]]
on = "x"
run = "remove"
desc = "Trash selected files"

[[manager.prepend_keymap]]
on = "X"
run = "Trash selected files"
desc = "Permanently delete selected files"

[[manager.prepend_keymap]]
on = "<C-q>"
run = "quit"
desc = "Exit the process"

[[manager.prepend_keymap]]
on = "<Enter>"
run = "shell $SHELL --block --confirm"
desc = "Open shell here"

[[manager.prepend_keymap]]
on = "<F1>"
run = "shell 'open -u https://yazi-rs.github.io/docs/quick-start#keybindings' --confirm"
desc = "Open keymaps"

[[manager.prepend_keymap]]
on = "<S-F1>"
run = "shell 'open -u https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml' --confirm"
desc = "Open default keymaps file"
