[default_view]

keymap = [
  # close
  { keys = ["ctrl+q"], command = "quit" },

  # cancel current operator
  { keys = ["escape"], command = "escape" },

  # tabs
  { keys = ["ctrl+t"], command = "new_tab" },
  { keys = ["alt+t"], command = "new_tab --cursor" },
  { keys = ["T"], command = "new_tab --current" },
  { keys = ["W"], command = "close_tab" },
  { keys = ["ctrl+w"], command = "close_tab" },

  # switch tabs
  { keys = ["\t"], command = "tab_switch 1" },
  { keys = ["backtab"], command = "tab_switch -1" },
  { keys = ["ctrl+1"], command = "tab_switch_index 1" },
  { keys = ["ctrl+2"], command = "tab_switch_index 2" },
  { keys = ["ctrl+3"], command = "tab_switch_index 3" },
  { keys = ["ctrl+4"], command = "tab_switch_index 4" },
  { keys = ["ctrl+5"], command = "tab_switch_index 5" },

  # refresh
  { keys = ["ctrl+r"], command = "reload_dirlist" },

  # toggle hidden files
  { keys = ["."], command = "toggle_hidden" },

  # map command to number
  { keys = ["1"], command = "numbered_command 1" },
  { keys = ["2"], command = "numbered_command 2" },
  { keys = ["3"], command = "numbered_command 3" },
  { keys = ["4"], command = "numbered_command 4" },
  { keys = ["5"], command = "numbered_command 5" },
  { keys = ["6"], command = "numbered_command 6" },
  { keys = ["7"], command = "numbered_command 7" },
  { keys = ["8"], command = "numbered_command 8" },
  { keys = ["9"], command = "numbered_command 9" },

  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["arrow_left"], command = "cd .." },
  { keys = ["arrow_right"], command = "open" },
  { keys = ["\n"], command = "open_with" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },
  { keys = ["page_up"], command = "cursor_move_page_up" },
  { keys = ["page_down"], command = "cursor_move_page_down" },
  { keys = ["ctrl+u"], command = "cursor_move_page_up 0.5" },
  { keys = ["ctrl+d"], command = "cursor_move_page_down 0.5" },

  # vim-like move keybindings
  { keys = ["j"], command = "cursor_move_down" },
  { keys = ["k"], command = "cursor_move_up" },
  { keys = ["h"], command = "cd .." },
  { keys = ["l"], command = "open" },
  { keys = ["g", "g"], command = "cursor_move_home" },
  { keys = ["G"], command = "cursor_move_end" },
  { keys = ["["], command = "parent_cursor_move_up" },
  { keys = ["]"], command = "parent_cursor_move_down" },

  # copy|cut files
  { keys = ["d", "d"], command = "cut_files" },
  { keys = ["y", "y"], command = "copy_files" },
  { keys = ["y", "n"], command = "copy_filename" },
  { keys = ["y", "."], command = "copy_filename_without_extension" },
  { keys = ["y", "p"], command = "copy_filepath" },
  { keys = ["y", "d"], command = "copy_dirpath" },

  # delete files
  { keys = ["delete"], command = "delete_files" },
  { keys = ["x"], command = "delete_files" },

  # paste files
  { keys = ["p", "p"], command = "paste_files" },
  { keys = ["p", "o"], command = "paste_files --overwrite=true" },
  { keys = ["p", "l"], command = "symlink_files --relative=false" },
  { keys = ["p", "L"], command = "symlink_files --relative=true" },

  # rename files
  { keys = ["r"], command = "rename_append" },
  { keys = ["R"], command = "bulk_rename" },

  # create files
  { keys = ["a"], command = ":shell touch " },
  { keys = ["A"], command = ":shell mkdir -p " },

  # select files
  { keys = [" "], command = "select --toggle=true" },
  { keys = ["V"], command = "toggle_visual" },

  # toggle task views
  { keys = ["w"], command = "show_tasks --exit-key=w" },

  # set access permissions
  { keys = ["="], command = "set_mode" },

  # input command
  { keys = [":"], command = ":" },
  { keys = [";"], command = ":" },
  { keys = ["'"], command = ":shell " },

  # search
  { keys = ["/"], command = ":search " },
  { keys = ["|"], command = ":search_inc " },
  { keys = ["\\"], command = ":search_glob " },
  { keys = ["S"], command = "search_fzf" },
  { keys = ["C"], command = "subdir_fzf" },
  { keys = ["n"], command = "search_next" },
  { keys = ["N"], command = "search_prev" },

  # sort
  { keys = ["s", "r"], command = "sort reverse" },
  { keys = ["s", "l"], command = "sort lexical" },
  { keys = ["s", "m"], command = "sort mtime" },
  { keys = ["s", "n"], command = "sort natural" },
  { keys = ["s", "s"], command = "sort size" },
  { keys = ["s", "e"], command = "sort ext" },

  # set show file info mode
  { keys = ["m", "s"], command = "linemode size" },
  { keys = ["m", "m"], command = "linemode mtime" },
  { keys = ["m", "M"], command = "linemode sizemtime" },

  # change directory
  { keys = ["c", "d"], command = ":cd " },
  { keys = ["g", "r"], command = "cd /" },
  { keys = ["g", "c"], command = "cd ~/.config" },
  { keys = ["g", "d"], command = "cd ~/Downloads" },
  { keys = ["g", "D"], command = "cd ~/Desktop" },
  { keys = ["g", "e"], command = "cd /etc" },
  { keys = ["g", "h"], command = "cd ~/" },
  { keys = ["?"], command = "help" },

  # open in finder
  { keys = ["O"], command = ":shell open ." },
]

[task_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },

  # vim-like move keybindings
  { keys = ["j"], command = "cursor_move_down" },
  { keys = ["k"], command = "cursor_move_up" },
  { keys = ["g", "g"], command = "cursor_move_home" },
  { keys = ["G"], command = "cursor_move_end" },
  { keys = ["w"], command = "show_tasks" },
  { keys = ["escape"], command = "show_tasks" },
]

[help_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },

  # vim-like move keybindings
  { keys = ["j"], command = "cursor_move_down" },
  { keys = ["k"], command = "cursor_move_up" },
  { keys = ["g", "g"], command = "cursor_move_home" },
  { keys = ["G"], command = "cursor_move_end" },

  { keys = ["w"], command = "show_tasks" },
  { keys = ["escape"], command = "show_tasks" },
]
